/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    Checkbox: typeof import('./src/components/ui/Checkbox.vue')['default']
    CheckboxComponent: typeof import('./src/components/ui/CheckboxComponent.vue')['default']
    ColorSwitchComponent: typeof import('./src/components/ui/ColorSwitchComponent.vue')['default']
    GreensparkLogo: typeof import('./src/assets/icons/GreensparkLogo.vue')['default']
    IconCheckboxTick: typeof import('./src/assets/icons/IconCheckboxTick.vue')['default']
    IconInfo: typeof import('./src/assets/icons/IconInfo.vue')['default']
    LoaderIcon: typeof import('./src/assets/icons/LoaderIcon.vue')['default']
    SvgIcon: typeof import('./src/components/essentials/SvgIcon.vue')['default']
    ToggleComponent: typeof import('./src/components/ui/ToggleComponent.vue')['default']
    TooltipComponent: typeof import('./src/components/ui/TooltipComponent.vue')['default']
    Widget: typeof import('./src/components/Widget.vue')['default']
    WidgetBadge: typeof import('./src/components/WidgetBadge.vue')['default']
    WidgetBadgeComponent: typeof import('./src/components/WidgetBadgeComponent.vue')['default']
    WidgetComponent: typeof import('./src/components/WidgetComponent.vue')['default']
    WidgetData: typeof import('./src/components/WidgetData.vue')['default']
    WidgetPanel: typeof import('./src/components/WidgetPanel.vue')['default']
    WidgetPanelComponent: typeof import('./src/components/WidgetPanelComponent.vue')['default']
    WidgetSettings: typeof import('./src/components/WidgetSettings.vue')['default']
    WidgetSettingsComponent: typeof import('./src/components/WidgetSettingsComponent.vue')['default']
  }
}
